# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_pb2 as music__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in music_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub:
    """── Serviços ───────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/music.UserService/CreateUser',
                request_serializer=music__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/music.UserService/ListUsers',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.UserList.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/music.UserService/GetUser',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/music.UserService/UpdateUser',
                request_serializer=music__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/music.UserService/DeleteUser',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GetUserPlaylists = channel.unary_unary(
                '/music.UserService/GetUserPlaylists',
                request_serializer=music__pb2.UserIdRequest.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)


class UserServiceServicer:
    """── Serviços ───────────────────────────────────────────────────

    """

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=music__pb2.CreateUserRequest.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.UserList.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=music__pb2.UpdateUserRequest.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.BoolResponse.SerializeToString,
            ),
            'GetUserPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPlaylists,
                    request_deserializer=music__pb2.UserIdRequest.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService:
    """── Serviços ───────────────────────────────────────────────────

    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/CreateUser',
            music__pb2.CreateUserRequest.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/ListUsers',
            music__pb2.Empty.SerializeToString,
            music__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/GetUser',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/UpdateUser',
            music__pb2.UpdateUserRequest.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/DeleteUser',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.UserService/GetUserPlaylists',
            music__pb2.UserIdRequest.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SongServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSong = channel.unary_unary(
                '/music.SongService/CreateSong',
                request_serializer=music__pb2.CreateSongRequest.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.ListSongs = channel.unary_unary(
                '/music.SongService/ListSongs',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.SongList.FromString,
                _registered_method=True)
        self.GetSong = channel.unary_unary(
                '/music.SongService/GetSong',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.UpdateSong = channel.unary_unary(
                '/music.SongService/UpdateSong',
                request_serializer=music__pb2.UpdateSongRequest.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.DeleteSong = channel.unary_unary(
                '/music.SongService/DeleteSong',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GetSongPlaylists = channel.unary_unary(
                '/music.SongService/GetSongPlaylists',
                request_serializer=music__pb2.SongIdRequest.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)


class SongServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SongServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSong,
                    request_deserializer=music__pb2.CreateSongRequest.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'ListSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSongs,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.SongList.SerializeToString,
            ),
            'GetSong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSong,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'UpdateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSong,
                    request_deserializer=music__pb2.UpdateSongRequest.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'DeleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSong,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.BoolResponse.SerializeToString,
            ),
            'GetSongPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongPlaylists,
                    request_deserializer=music__pb2.SongIdRequest.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.SongService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.SongService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SongService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/CreateSong',
            music__pb2.CreateSongRequest.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/ListSongs',
            music__pb2.Empty.SerializeToString,
            music__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/GetSong',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/UpdateSong',
            music__pb2.UpdateSongRequest.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/DeleteSong',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.SongService/GetSongPlaylists',
            music__pb2.SongIdRequest.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaylistServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePlaylist = channel.unary_unary(
                '/music.PlaylistService/CreatePlaylist',
                request_serializer=music__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.ListPlaylists = channel.unary_unary(
                '/music.PlaylistService/ListPlaylists',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.GetPlaylist = channel.unary_unary(
                '/music.PlaylistService/GetPlaylist',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.UpdatePlaylist = channel.unary_unary(
                '/music.PlaylistService/UpdatePlaylist',
                request_serializer=music__pb2.UpdatePlaylistRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/music.PlaylistService/DeletePlaylist',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.AddSongToPlaylist = channel.unary_unary(
                '/music.PlaylistService/AddSongToPlaylist',
                request_serializer=music__pb2.PlaylistSongRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.RemoveSongFromPlaylist = channel.unary_unary(
                '/music.PlaylistService/RemoveSongFromPlaylist',
                request_serializer=music__pb2.PlaylistSongRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.GetPlaylistSongs = channel.unary_unary(
                '/music.PlaylistService/GetPlaylistSongs',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.SongList.FromString,
                _registered_method=True)


class PlaylistServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSongToPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSongFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaylistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=music__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'ListPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylists,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
            'GetPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylist,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'UpdatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylist,
                    request_deserializer=music__pb2.UpdatePlaylistRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.BoolResponse.SerializeToString,
            ),
            'AddSongToPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSongToPlaylist,
                    request_deserializer=music__pb2.PlaylistSongRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'RemoveSongFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSongFromPlaylist,
                    request_deserializer=music__pb2.PlaylistSongRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'GetPlaylistSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistSongs,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.SongList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.PlaylistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.PlaylistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaylistService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/CreatePlaylist',
            music__pb2.CreatePlaylistRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/ListPlaylists',
            music__pb2.Empty.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/GetPlaylist',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/UpdatePlaylist',
            music__pb2.UpdatePlaylistRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/DeletePlaylist',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSongToPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/AddSongToPlaylist',
            music__pb2.PlaylistSongRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSongFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/RemoveSongFromPlaylist',
            music__pb2.PlaylistSongRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.PlaylistService/GetPlaylistSongs',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
